export {
  type HealthResponse,
  HealthResponseSchema
} from "./schemas/health";

export { createApiClient, type ApiClient } from "./api/client";
export {
  computePrerequisitePath,
  type PrerequisitePathCycle,
  type PrerequisitePathOk,
  type PrerequisitePathResult
} from "./learning-path";

export { isPrereqEdge, getPrereqDirection, EDGE_TYPE_CATEGORIES, getDefaultEdgeTypes, type EdgeTypeCategory } from "./edge-semantics";
export { computeGraphLens, type GraphLensInput, type GraphLensResult } from "./graph-lens";
export { wouldCreatePrereqCycle, type CycleCheckResult } from "./cycle-detection";
export { computePageRank, type PageRankEdge, type PageRankOptions } from "./pagerank";
export { detectCommunities, type CommunityEdge, type CommunityDetectionOptions } from "./community-detection";

export {
  ApiErrorSchema,
  type ApiError,
  ConceptSchema,
  type Concept,
  ConceptSummarySchema,
  type ConceptSummary,
  SourceSchema,
  type Source,
  ChunkSchema,
  type Chunk,
  EdgeSchema,
  type Edge,
  EdgeEvidenceSchema,
  type EdgeEvidence,
  EdgeSummarySchema,
  type EdgeSummary,
  EdgeTypeSchema,
  type EdgeType,
  NodeKindSchema,
  type NodeKind,
  GetConceptParamsSchema,
  type GetConceptParams,
  GetEdgeParamsSchema,
  type GetEdgeParams,
  GetSourceParamsSchema,
  type GetSourceParams,
  GetConceptResponseSchema,
  type GetConceptResponse,
  SummaryLevelsSchema,
  type SummaryLevels,
  DraftRevisionStatusSchema,
  type DraftRevisionStatus,
  DraftRevisionKindSchema,
  type DraftRevisionKind,
  DraftRevisionSchema,
  type DraftRevision,
  PostConceptDistillResponseSchema,
  type PostConceptDistillResponse,
  GetConceptDraftRevisionsResponseSchema,
  type GetConceptDraftRevisionsResponse,
  PostDraftRevisionApplyResponseSchema,
  type PostDraftRevisionApplyResponse,
  PostDraftRevisionRejectResponseSchema,
  type PostDraftRevisionRejectResponse,
  PostDraftRevisionRevertResponseSchema,
  type PostDraftRevisionRevertResponse,
  GetEdgeEvidenceResponseSchema,
  type GetEdgeEvidenceResponse,
  GetConceptSourcesResponseSchema,
  type GetConceptSourcesResponse,
  GraphQuerySchema,
  type GraphQuery,
  GraphResponseSchema,
  type GraphResponse,
  ClusterSchema,
  type Cluster,
  GraphClusteredResponseSchema,
  type GraphClusteredResponse,
  GraphLensQuerySchema,
  type GraphLensQuery,
  GraphLensResponseSchema,
  type GraphLensResponse,
  ShortestPathQuerySchema,
  type ShortestPathQuery,
  ShortestPathResponseSchema,
  type ShortestPathResponse,
  LensSideSchema,
  type LensSide,
  LensNodeMetadataSchema,
  type LensNodeMetadata,
  PostConceptRequestSchema,
  type PostConceptRequest,
  PostConceptResponseSchema,
  type PostConceptResponse,
  PostConceptSourceRequestSchema,
  type PostConceptSourceRequest,
  PostConceptSourceResponseSchema,
  type PostConceptSourceResponse,
  PostConceptLocalSourceRequestSchema,
  type PostConceptLocalSourceRequest,
  PostConceptLocalSourceResponseSchema,
  type PostConceptLocalSourceResponse,
  GetSourceContentResponseSchema,
  type GetSourceContentResponse,
  PostSourceContentRequestSchema,
  type PostSourceContentRequest,
  PostSourceContentResponseSchema,
  type PostSourceContentResponse,
  PostEdgeRequestSchema,
  type PostEdgeRequest,
  PostEdgeResponseSchema,
  type PostEdgeResponse,
  PostDraftEdgeRequestSchema,
  type PostDraftEdgeRequest,
  PostDraftEdgeResponseSchema,
  type PostDraftEdgeResponse,
  PostCrawlRequestSchema,
  type PostCrawlRequest,
  PostCrawlResponseSchema,
  type PostCrawlResponse,
  SearchModeSchema,
  type SearchMode,
  SearchQuerySchema,
  type SearchQuery,
  SearchResponseSchema,
  type SearchResponse,
  ExactSearchResultSchema,
  type ExactSearchResult,
  SearchExactResponseSchema,
  type SearchExactResponse,
  SearchUniversalQuerySchema,
  type SearchUniversalQuery,
  SourceSearchResultSchema,
  type SourceSearchResult,
  EvidenceSearchResultSchema,
  type EvidenceSearchResult,
  SearchUniversalResponseSchema,
  type SearchUniversalResponse,
  ChangesetStatusSchema,
  type ChangesetStatus,
  ChangesetSchema,
  type Changeset,
  ChangesetItemStatusSchema,
  type ChangesetItemStatus,
  ChangesetItemSchema,
  type ChangesetItem,
  ChangesetFilePatchPayloadSchema,
  type ChangesetFilePatchPayload,
  EvidenceChunkSchema,
  type EvidenceChunk,
  GetChangesetsResponseSchema,
  type GetChangesetsResponse,
  GetChangesetParamsSchema,
  type GetChangesetParams,
  GetChangesetResponseSchema,
  type GetChangesetResponse,
  ChangesetItemParamsSchema,
  type ChangesetItemParams,
  PostChangesetItemStatusRequestSchema,
  type PostChangesetItemStatusRequest,
  PostChangesetItemStatusResponseSchema,
  type PostChangesetItemStatusResponse,
  PostApplyChangesetResponseSchema,
  type PostApplyChangesetResponse,
  PostChangesetStatusRequestSchema,
  type PostChangesetStatusRequest,
  PostChangesetStatusResponseSchema,
  type PostChangesetStatusResponse,
  QuizTypeSchema,
  type QuizType,
  ReviewItemStatusSchema,
  type ReviewItemStatus,
  QuizItemSchema,
  type QuizItem,
  ReviewGradeSchema,
  type ReviewGrade,
  GetReviewDueQuerySchema,
  type GetReviewDueQuery,
  GetReviewDueResponseSchema,
  type GetReviewDueResponse,
  ReviewItemParamsSchema,
  type ReviewItemParams,
  PostReviewGradeRequestSchema,
  type PostReviewGradeRequest,
  PostReviewGradeResponseSchema,
  type PostReviewGradeResponse,
  GetConceptQuizzesResponseSchema,
  type GetConceptQuizzesResponse,
  PostGenerateConceptQuizzesRequestSchema,
  type PostGenerateConceptQuizzesRequest,
  PostGenerateConceptQuizzesResponseSchema,
  type PostGenerateConceptQuizzesResponse,
  TutorAnswerSchema,
  type TutorAnswer,
  PostTutorRequestSchema,
  type PostTutorRequest,
  PostTutorResponseSchema,
  type PostTutorResponse,
  PostConceptMergePreviewRequestSchema,
  type PostConceptMergePreviewRequest,
  PostConceptMergePreviewResponseSchema,
  type PostConceptMergePreviewResponse,
  ConceptMergeEdgeChangeSchema,
  type ConceptMergeEdgeChange,
  ConceptMergeSchema,
  type ConceptMerge,
  PostConceptMergeApplyRequestSchema,
  type PostConceptMergeApplyRequest,
  PostConceptMergeApplyResponseSchema,
  type PostConceptMergeApplyResponse,
  ConceptMergeParamsSchema,
  type ConceptMergeParams,
  PostConceptMergeUndoResponseSchema,
  type PostConceptMergeUndoResponse,
  GetConceptMergesResponseSchema,
  type GetConceptMergesResponse,
  ContextPackRadiusSchema,
  type ContextPackRadius,
  PostContextPackRequestSchema,
  type PostContextPackRequest,
  PostContextPackResponseSchema,
  type PostContextPackResponse,
  PostCaptureRequestSchema,
  type PostCaptureRequest,
  PostCaptureResponseSchema,
  type PostCaptureResponse,
  TrainingQuestionTypeSchema,
  type TrainingQuestionType,
  MechanismTraceAnswerSchema,
  type MechanismTraceAnswer,
  FailureModeAnswerSchema,
  type FailureModeAnswer,
  ContrastExplainAnswerSchema,
  type ContrastExplainAnswer,
  CodeReasoningAnswerSchema,
  type CodeReasoningAnswer,
  TrainingRubricSchema,
  type TrainingRubric,
  TrainingSessionStatusSchema,
  type TrainingSessionStatus,
  TrainingSessionSchema,
  type TrainingSession,
  TrainingSessionItemGradeSchema,
  type TrainingSessionItemGrade,
  TrainingSessionItemSchema,
  type TrainingSessionItem,
  TrainingQuizItemSchema,
  type TrainingQuizItem,
  PostCreateTrainingSessionRequestSchema,
  type PostCreateTrainingSessionRequest,
  PostCreateTrainingSessionResponseSchema,
  type PostCreateTrainingSessionResponse,
  TrainingSessionParamsSchema,
  type TrainingSessionParams,
  GetTrainingSessionResponseSchema,
  type GetTrainingSessionResponse,
  TrainingSessionItemParamsSchema,
  type TrainingSessionItemParams,
  PostSubmitTrainingAnswerRequestSchema,
  type PostSubmitTrainingAnswerRequest,
  PostSubmitTrainingAnswerResponseSchema,
  type PostSubmitTrainingAnswerResponse,
  PostCompleteTrainingSessionResponseSchema,
  type PostCompleteTrainingSessionResponse,
  GetConceptNoteResponseSchema,
  type GetConceptNoteResponse,
  PostConceptNoteRequestSchema,
  type PostConceptNoteRequest,
  PostConceptNoteResponseSchema,
  type PostConceptNoteResponse,
  GetConceptBacklinksResponseSchema,
  type GetConceptBacklinksResponse,
  PostGenerateConceptContextResponseSchema,
  type PostGenerateConceptContextResponse,
  PostUpdateConceptContextRequestSchema,
  type PostUpdateConceptContextRequest,
  PostUpdateConceptContextResponseSchema,
  type PostUpdateConceptContextResponse
} from "./schemas/api-v1";

export { getConcept, getGraph } from "./api/client";
